[features]
seeds = false
skip-lint = false



[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./funvWGBmpr8N7pTNqpxkWPgWnQbL3Yr5vzCHNJT2YkL.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
